services:
  - type: web
    name: wallframe-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: wallframe
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: public/uploads
      - key: API_BASE_URL
        value: https://wall-frame-full-project.onrender.com

  - type: web
    name: wallframe-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://wall-frame-full-project.onrender.com