services:
  - type: web
    name: wall-frame-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: BASIC_PLAN_DRAFTS
        value: 3
      - key: PRO_PLAN_DRAFTS
        value: 6
      - key: PRO_MAX_PLAN_DRAFTS
        value: 999

  - type: web
    name: wall-frame-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://wall-frame-full-project.onrender.com
      - key: REACT_APP_ENABLE_EMAIL_NOTIFICATIONS
        value: true
      - key: REACT_APP_ENABLE_FILE_UPLOAD
        value: true
      - key: REACT_APP_ENABLE_ADMIN_PANEL
        value: true
      - key: REACT_APP_MAX_FILE_SIZE
        value: 5242880 